name: Rust CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions/setup-rust@v2
      with:
        rust-version: '1.55.0'

    - name: Build and test
      run: cargo make test
